In [1]:
import numpy as np
from numpy.linalg import inv
from sympy import Matrix

T = np.array([
    [0, 1, 1, 0],
    [0, 1, 0, 0],
    [1, 0, 0, 0],
    [0, 0, 0, 1]
], dtype=float)

print("inverst(T)")
print(inv(T))

inverst(T)
[[ 0.  0.  1.  0.]
 [ 0.  1.  0.  0.]
 [ 1. -1.  0.  0.]
 [ 0.  0.  0.  1.]]


In [2]:
# access x
A_x = [
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 0]
]
offset_x = np.array([0, -1, 0, 0], dtype=float)

# print("null space of A_x:")
# A_x = Matrix(A_x)
# print(A1.nullspace())

print("transformed A_x:")
A_x = np.array(A_x, dtype=float)
print(A_x @ T)
print("transformed offset:")
print(offset_x.transpose() @ T)

transformed A_x:
[[0. 1. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]]
transformed offset:
[ 0. -1.  0.  0.]


In [3]:
# access s

A_s = [
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 1]
]
offset_s = np.array([0, 0, -1, 0], dtype=float)

# print("\nnull space of A_s:")
# A_s = Matrix(A_s)
# print(A_s.nullspace())

print("\ntransformed A_s:")
A_s = np.array(A_s, dtype=float)
print(A_s @ T)
print("transformed offset:")
print(offset_s.transpose() @ T)


transformed A_s:
[[0. 1. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]
transformed offset:
[-1.  0.  0.  0.]


In [4]:
# access w
A_w = [
    [0, 1, 0, 0],
    [0, 0, 0, 1],
    [0, 0, 0, 0],
    [0, 0, 0, 0]
]
# print("\nnull space of A_w:")
# A_w = Matrix(A_w)
# print(A_w.nullspace())

print("\ntransformed A_w:")
A_w = np.array(A_w, dtype=float)
print(A_w @ T)


transformed A_w:
[[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
T2 = np.array([
    [0, 1, 1, 0],
    [0, 0, 1, 0],
    [1, 0, 0, 0],
    [0, 0, 0, 1]
], dtype=float)

print("inverst(T2)")
print(inv(T2))

inverst(T2)
[[ 0.  0.  1.  0.]
 [ 1. -1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  0.  1.]]


In [6]:
print("transformed A_x:")
A_x = np.array(A_x, dtype=float)
print(A_x @ T2)
print("transformed offset:")
print(offset_x.transpose() @ T2)

transformed A_x:
[[0. 1. 1. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]]
transformed offset:
[ 0.  0. -1.  0.]


In [7]:
print("\ntransformed A_s:")
A_s = np.array(A_s, dtype=float)
print(A_s @ T2)
print("transformed offset:")
print(offset_s.transpose() @ T2)


transformed A_s:
[[0. 1. 1. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]
transformed offset:
[-1.  0.  0.  0.]


In [8]:
print("\ntransformed A_w:")
A_w = np.array(A_w, dtype=float)
print(A_w @ T2)


transformed A_w:
[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
